query SELLER_INVOICES($sellerInvoiceParams: SellerInvoiceParams) {
  invoicesBySeller(sellerInvoiceParams: $sellerInvoiceParams) {
    data{
      id
      status
      invoiceCreatedDate
      totalizers {
        subtotal
        fee
        total
      }
    }
    pagination {
      total
      page
      pageSize
    }
  }
}





