query SELLER_INVOICES($sellerInvoiceParams: SellerInvoiceParams) {
  invoicesBySeller(sellerInvoiceParams: $sellerInvoiceParams) {
    invoiceCreatedDate
    status
    totalizers {
      subtotal
      fee
      total
    }
  }
}





